### ISSUE TITLE
java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by teddis** [ArthurHub/Android-Image-Cropper#1]
First, thank you so much for this library. It's awesome and using it with my app. But I just got this error from Crashlytics from the field. Sounds like an incompatible binary with source. Does the library just need to be rebuilt and published to moven? 

```
java.lang.IncompatibleClassChangeError: interface not implemented
       at com.theartofdev.edmodo.cropper.util.ImageViewUtil.closeSafe(ImageViewUtil.java:252)
       at com.theartofdev.edmodo.cropper.util.ImageViewUtil.getFileFromUri(ImageViewUtil.java:225)
       at com.theartofdev.edmodo.cropper.util.ImageViewUtil.rotateBitmapByExif(ImageViewUtil.java:94)
       at com.theartofdev.edmodo.cropper.CropImageView.setImageUri(CropImageView.java:293)
       at com.gameontechnology.gameon.ui.activity.PhotoPickerActivity.onActivityResult(PhotoPickerActivity.java:88)
       at android.app.Activity.dispatchActivityResult(Activity.java:4670)
```

**Comment by ArthurHub** [comment]
Looks like API bug, Cursor didn't implement Closeable.
Fixed and published 1.0.4
