### ISSUE TITLE
>=Marshmellow CRASH. IllegalStateException: Underflow in restore - more restores than saves

### ISSUE THREAD

**Issue by urlop** [ArthurHub/Android-Image-Cropper#102]
Hi, I'm getting the following crash when I try to fill the CropImageView after I get an image from the gallery:

```
java.lang.IllegalStateException: Underflow in restore - more restores than saves
           at android.graphics.Canvas.native_restore(Native Method)
           at android.graphics.Canvas.restore(Canvas.java:571)
           at com.theartofdev.edmodo.cropper.cropwindow.CropOverlayView.drawBackground(CropOverlayView.java:555)
           at com.theartofdev.edmodo.cropper.cropwindow.CropOverlayView.onDraw(CropOverlayView.java:312)
```

Everything was working fine until I tried it on Samsung S6 (Android version 6.0.1).

Here is the code to insert the image:
```java
@Override
    protected void onActivityResult(int  requestCode, int resultCode, Intent data) {
        if (resultCode == Activity.RESULT_OK) {
            imageUri =  data.getData();
            civ_image.setImageUri(imageUri);
        }else{
            if(imageUri == null){
                finish();
            }
        }
    }
```

**Comment by ArthurHub** [comment]
that is very strange.. are you using the latest version?

**Comment by urlop** [comment]
You are right. I was using version 1.0.1. I updated to the latest one (2.2.3) and now it works perfect.
Sorry for the inconvenient.
CLOSED.

**Comment by ArthurHub** [comment]
No problem, many new features since 1.*, check the [change log](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Change-Log).
