### ISSUE TITLE
ClassCastException on findViewById of CropOverlayView

### ISSUE THREAD

**Issue by HassanJawed** [ArthurHub/Android-Image-Cropper#180]
Here is how I added CropImageView in one of my Fragments and it is crashing..

```
<com.theartofdev.edmodo.cropper.CropImageView
            android:layout_width="152dp"
            android:layout_height="0dp"
            app:cropShape="oval"
            app:cropGuidelines="off"
            app:cropAutoZoomEnabled="false"
            app:cropFixAspectRatio="true"
            app:cropSnapRadius="76dp"
            app:cropShowCropOverlay="false"
            android:layout_centerInParent="true"
            />
```

Here are the details of the crash

```
Caused by: java.lang.ClassCastException: com.edmodo.cropper.cropwindow.CropOverlayView cannot be cast to com.theartofdev.edmodo.cropper.CropOverlayView
                                                                               at com.theartofdev.edmodo.cropper.CropImageView.<init>(CropImageView.java:267)
                                                                               at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                               at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                               at android.view.LayoutInflater.createView(LayoutInflater.java:607) 
```

I searched SO as well, couldn't find fix

**Comment by anilbisht** [comment]
There are two different packages for same view. In XML  try com.edmodo.cropper.cropwindow.CropOverlayView TAG.

**Comment by ArthurHub** [comment]
Looks like you have dependency problem, make sure you only have one dependency on the latest version of this library and not [edmodo/cropper](https://github.com/edmodo/cropper)

**Comment by HassanJawed** [comment]
I checked, one my app's dependency library is using [edmodo/cropper](https://github.com/edmodo/cropper) and I cannot remove that library as some of my apps functionality is dependent on it. Any idea on how to fix it on Android-image-cropper part?

**Comment by HassanJawed** [comment]
I renamed, layout/crop_image_view to layout/aic_crop_image_view because same layout is present in [edmodo/cropper](https://github.com/edmodo/cropper) and is causing this conflict. So renaming layout did the trick for me.
