### ISSUE TITLE
resultUri is retuning null after selecting image

### ISSUE THREAD

**Issue by immyemperor** [ArthurHub/Android-Image-Cropper#201]
if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
            CropImage.ActivityResult result = CropImage.getActivityResult(data);
            if (resultCode == RESULT_OK) {
                resultUri = result.getUri();// this is returnig null
                mybitmap = result.getBitmap();

            } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
                Exception error = result.getError();
            }
        }

**Comment by nikhil19patil** [comment]
Also in following callback

```
@Override
public void onCropImageComplete(CropImageView view, CropImageView.CropResult result) {
    Uri uri = result.getUri();// uri is getting null
}
```

**Comment by ArthurHub** [comment]
As the documentation explains the Bitmap or Uri can be null depending on the API executed and failure.

```
/**
 * The cropped image bitmap result.<br>
 * Null if save cropped image was executed, no output requested or failure.
 */
public Bitmap getBitmap() {
  return mBitmap;
}

/**
 * The Android uri of the saved cropped image result
 * Null if get cropped image was executed, no output requested or failure.
 */
public Uri getUri() {
  return mUri;
}
```

**Comment by immyemperor** [comment]
if (requestCode == CropImage.CROP_IMAGE_ACTIVITY_REQUEST_CODE) {
            CropImage.ActivityResult result = CropImage.getActivityResult(data);
            if (resultCode == RESULT_OK) {
               Uri resultUri = result.getUri();
                imageUri=resultUri;
                mybitmap = result.getBitmap();
                profilePicBtn.setImageURI(imageUri);
                saveToInternalStorage(mybitmap);


            } else if (resultCode == CropImage.CROP_IMAGE_ACTIVITY_RESULT_ERROR_CODE) {
                Exception error = result.getError();
            }
        }
        if(requestCode==Gallary_Intent && requestCode==RESULT_OK) {
           
            Uri uri = data.getData();
            CropImage.activity(uri).setAspectRatio(1,1)
                    .start(getContext(), Account_setting.this);
            showProgressDialog();
            StorageReference filepath = mStorage.child("profile_pictures").child(mfirebaseuser.getUid());
            filepath.putFile(imageUri).addOnSuccessListener(new OnSuccessListener<UploadTask.TaskSnapshot>() {
                @Override
                public void onSuccess(UploadTask.TaskSnapshot taskSnapshot) {



                    //setting imageview to show image
                    Uri downloadUri= taskSnapshot.getDownloadUrl();

                    String download_url=downloadUri.toString();
                    DatabaseReference fref =mref.child(mfirebaseuser.getUid()).child("image_uri");
                    fref.setValue(download_url);
                   // profilePicBtn.setImageURI(downloadUri);
                    //Picasso.with(getActivity()).load(downloadUri).fit().centerCrop().into(profilePicBtn);
                    hideProgressDialog();
                    Toast.makeText(getActivity(), R.string.profile_pic_success,
                            Toast.LENGTH_SHORT).show();

                }
            }).addOnFailureListener(new OnFailureListener() {
                @Override
                public void onFailure(@NonNull Exception e) {
                    hideProgressDialog();
                    Toast.makeText(getActivity(), R.string.profile_pic_failure,
                            Toast.LENGTH_SHORT).show();
                }
            });

        }



its giving error

E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65537, result=-1, data=Intent { dat=content://media/external/images/media/39673 (has extras) }} to activity {com.mapmyindia.emperors.raaste/com.mapmyindia.emperors.raaste.MainActivity}: java.lang.IllegalArgumentException: uri cannot be null
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3209)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3252)
                      at android.app.ActivityThread.access$1200(ActivityThread.java:143)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:137)
                      at android.app.ActivityThread.main(ActivityThread.java:4960)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:511)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.IllegalArgumentException: uri cannot be null
                      at com.google.android.gms.common.internal.zzaa.zzb(Unknown Source)
                      at com.google.firebase.storage.StorageReference.putFile(Unknown Source)
                      at com.mapmyindia.emperors.raaste.fragments.Account_setting.onActivityResult(Account_setting.java:257)
                      at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:167)
                      at android.app.Activity.dispatchActivityResult(Activity.java:5387)
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:3205)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:3252) 
                      at android.app.ActivityThread.access$1200(ActivityThread.java:143) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1289) 
                      at android.os.Handler.dispatchMessage(Handler.java:99) 
                      at android.os.Looper.loop(Looper.java:137) 
                      at android.app.ActivityThread.main(ActivityThread.java:4960) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:511) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1038) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:805) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by immyemperor** [comment]
i know the document says it can return null but why it is returning null when i am doing everything right...plz help me fix this issue.....and one thing more when i am not passing imageuri into putfile...crop image activity is working i can select and corp image but when i am passing argument to putfile its returning null

**Comment by immyemperor** [comment]
i figured it out...i moved my code to if statement of image corp activity result..its working now...thanks buddy for letting us use image cropper

**Comment by Mutaquiha** [comment]
I'm having the same problem with onCropImageComplete, it returns correctly the bitmap, but it seems that is failing to register the Uri, is there someone with the same problem? Thank you;

**Comment by ArthurHub** [comment]
It is not an error, please read the method documentation.

**Comment by Mutaquiha** [comment]
Hi Arthur, I found the problem in my code, I was not calling the saveCroppedImageAsync(uri) after the getCroppedImageAsync().

**Comment by liauli** [comment]
@Mutaquiha hello there, can you share how you crop the image? I tried with code blow but not working, still getting null for result.getUri(). Thanks!


```
public void crop(){
     cropImageView.setOnCropImageCompleteListener(new CropImageView.OnCropImageCompleteListener() {
                 @Override
                 public void onCropImageComplete(CropImageView view, CropImageView.CropResult result) {
                     if(result.getUri()!=null)Log.e("tes-result",result.getUri().toString()); //null
                     if(croppedUri!=null)Log.e("tes - croppeduri", croppedUri.toString()); //null too
                 }
             });
     cropImageView.getCroppedImageAsync();
     cropImageView.saveCroppedImageAsync(croppedUri);
}
```

**Comment by akshaykumarboth** [comment]
Hi, 

I am trying to implement crop image view in own custom activity. I am getting cropped bitmap successfully but result.getUri() in onCropImageComplete inside setOnCropImageCompleteListener is giving null. Please share a working example.
