### ISSUE TITLE
FileNotFoundException while writing bitmap to uri

### ISSUE THREAD

**Issue by ankitbatra11** [ArthurHub/Android-Image-Cropper#211]
Got this exception in prod via analytics:

Non-fatal Exception: java.io.FileNotFoundException: Permission denied
       at android.os.Parcel.openFileDescriptor(Parcel.java)
       at android.os.ParcelFileDescriptor.openInternal(ParcelFileDescriptor.java:253)
       at android.os.ParcelFileDescriptor.open(ParcelFileDescriptor.java:199)
       at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:936)
       at android.content.ContentResolver.openOutputStream(ContentResolver.java:706)
       at android.content.ContentResolver.openOutputStream(ContentResolver.java:682)
       at com.theartofdev.edmodo.cropper.BitmapUtils.writeBitmapToUri(SourceFile:295)
       at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.doInBackground(SourceFile:199)
       at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.doInBackground(SourceFile:25)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by leduyhung** [comment]
Permission denied! are you add permision in your manifests ?

**Comment by ankitbatra11** [comment]
Yes.

**Comment by ankitbatra11** [comment]
Here are the permissions from manifest file:


    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.WRITE_SETTINGS"/>

    
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
    <uses-permission android:name="com.android.vending.BILLING"/>

    
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>

**Comment by ArthurHub** [comment]
Did you create the output path yourself or is it the library default?

**Comment by ankitbatra11** [comment]
I created it.

**Comment by ArthurHub** [comment]
I think you created it in a location that may require other permissions.
How did you create it?
What device and android version it happens on?

**Comment by ankitbatra11** [comment]
Will share details from analytics.
