### ISSUE TITLE
TransactionTooLargeException on Android 7 Nougat

### ISSUE THREAD

**Issue by ankitbatra11** [ArthurHub/Android-Image-Cropper#269]
CropImageView.onSaveInstanceState is broken on android 7 devices.

I am using CropImageView in a fragment with a share action. On share action click,

1. I save the cropped image to a file.
2. Create a content uri for the file using file provider and
3. Share the uri with other apps.

Every time I am doing that, I am hitting:

```
Fatal Exception: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 8298076 bytes
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3806)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6120)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by android.os.TransactionTooLargeException: data parcel size 8298076 bytes
       at android.os.BinderProxy.transactNative(Binder.java)
       at android.os.BinderProxy.transact(Binder.java:615)
       at android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3621)
       at android.app.ActivityThread$StopInfo.run(ActivityThread.java:3798)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6120)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

I was suspecting it to be the new stringent limits on parcelled data in Android Nougat. So, I extended the CropImageView as below and used it in my fragment:

```
public class CustomCropImageView extends CropImageView {

    public CustomCropImageView(Context context) {
        super(context);
    }

    public CustomCropImageView(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public Parcelable onSaveInstanceState() {
        setImageBitmap(null);
        return super.onSaveInstanceState();
    }
}

```

The above hack fixed the crash for me.

Here is the fragment if you want to take a look at:

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical">

    <my.app.package.ui.edit.CustomCropImageView
        android:id="@+id/image_view"
        android:layout_width="match_parent"
        android:layout_height="0dip"
        android:layout_weight="1"
        app:cropInitialCropWindowPaddingRatio="0"
        tools:src="@drawable/ic_crop_black_24dp"/>

    <android.support.v7.widget.LinearLayoutCompat
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:orientation="horizontal"
        app:divider="@drawable/divider_vertical"
        app:showDividers="middle"
        tools:ignore="PrivateResource">

        <android.support.v7.widget.AppCompatImageView
            android:id="@+id/rotate"
            android:layout_width="0dip"
            android:layout_height="40dp"
            android:layout_weight="1"
            android:background="?attr/selectableItemBackground"
            android:paddingBottom="8dp"
            android:paddingTop="8dp"
            android:scaleType="fitCenter"
            android:tint="@android:color/black"
            app:srcCompat="@drawable/ic_rotate_right_black_24dp"/>

        <android.support.v7.widget.AppCompatImageView
            android:id="@+id/crop"
            android:layout_width="0dip"
            android:layout_height="40dp"
            android:layout_weight="1"
            android:background="?attr/selectableItemBackground"
            android:paddingBottom="8dp"
            android:paddingTop="8dp"
            android:scaleType="fitCenter"
            android:tint="@android:color/black"
            app:srcCompat="@drawable/ic_done_white_24dp"/>
    </android.support.v7.widget.LinearLayoutCompat>

</LinearLayout>
```

**Comment by ArthurHub** [comment]
Duplicate to #244.
It seems to be more common than I imagined, I will create a workaround in the next version.
