### ISSUE TITLE
Crash from production

### ISSUE THREAD

**Issue by arams** [ArthurHub/Android-Image-Cropper#281]
`Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.net.Uri.equals(java.lang.Object)' on a null object reference
       at com.theartofdev.edmodo.cropper.CropImageActivity.getOutputUri(CropImageActivity.java:194)
       at com.theartofdev.edmodo.cropper.CropImageActivity.cropImage(CropImageActivity.java:171)
       at com.theartofdev.edmodo.cropper.CropImageActivity.onOptionsItemSelected(CropImageActivity.java:119)
       at android.app.Activity.onMenuItemSelected(Activity.java:2940)
       at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:421)
       at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:188)
       at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:103)
       at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:663)
       at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
       at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
       at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:947)
       at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
       at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:155)
       at android.view.View.performClick(View.java:4855)
       at android.view.View$PerformClick.run(View.java:20287)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5653)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)`

**Comment by arams** [comment]
we were using 
    `compile 'com.theartofdev.edmodo:android-image-cropper:2.3.+'`

**Comment by ArthurHub** [comment]
Do you use `ActivityBuilder.setOutputUri()` method?
Looking at the code there is no flow that sets this field to null...

**Comment by ArthurHub** [comment]
I will also add a check if it's null in the next version
