### ISSUE TITLE
stack over flow issues with firebase storage

### ISSUE THREAD

**Issue by ViRu-ThE-ViRuS** [ArthurHub/Android-Image-Cropper#313]
`06-20 00:17:13.042 15837-15837/com.viru_rocks.covfefe_2 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.viru_rocks.covfefe_2, PID: 15837
                                                                          java.lang.StackOverflowError: stack size 8MB
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzao(Unknown Source)
                                                                              at com.google.android.gms.internal.yx.zzar(Unknown Source)
                                                                              at com.google.android.gms.internal.yy.zzas(Unknown Source)
                                                                          	at com.google.android.gms.internal.yx.zzao(Unknown Sou`

**Comment by ArthurHub** [comment]
how is this related to the library?
