### ISSUE TITLE
Error when trying to get the result

### ISSUE THREAD

**Issue by mvp-sales** [ArthurHub/Android-Image-Cropper#316]
The crop does not fail but this exception stops my `ImageView` from being updated.

```
E/Parcel: Class not found when unmarshalling: com.theartofdev.edmodo.cropper.CropImageOptions
                                       java.lang.ClassNotFoundException: com.theartofdev.edmodo.cropper.CropImageOptions
                                           at java.lang.Class.classForName(Native Method)
                                           at java.lang.Class.forName(Class.java:309)
                                           at java.lang.Class.forName(Class.java:273)
                                           at android.os.Parcel.readParcelableCreator(Parcel.java:2281)
                                           at android.os.Parcel.readParcelable(Parcel.java:2245)
                                           at android.os.Parcel.readValue(Parcel.java:2152)
                                           at android.os.Parcel.readArrayMapInternal(Parcel.java:2485)
                                           at android.os.BaseBundle.unparcel(BaseBundle.java:221)
                                           at android.os.BaseBundle.getString(BaseBundle.java:918)
                                           at android.content.Intent.getStringExtra(Intent.java:5854)
                                           at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2569)
                                           at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2039)
                                           at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5851)
                                           at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5629)
                                           at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:146)
                                           at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3723)
                                           at android.os.Binder.execTransact(Binder.java:446)
                                        Caused by: java.lang.ClassNotFoundException: Didn't find class "com.theartofdev.edmodo.cropper.CropImageOptions" on path: DexPathList[[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                           at java.lang.Class.classForName(Native Method) 
                                           at java.lang.Class.forName(Class.java:309) 
                                           at java.lang.Class.forName(Class.java:273) 
                                           at android.os.Parcel.readParcelableCreator(Parcel.java:2281) 
                                           at android.os.Parcel.readParcelable(Parcel.java:2245) 
                                           at android.os.Parcel.readValue(Parcel.java:2152) 
                                           at android.os.Parcel.readArrayMapInternal(Parcel.java:2485) 
                                           at android.os.BaseBundle.unparcel(BaseBundle.java:221) 
                                           at android.os.BaseBundle.getString(BaseBundle.java:918) 
                                           at android.content.Intent.getStringExtra(Intent.java:5854) 
                                           at com.android.server.am.ActivityStackSupervisor.startActivityLocked(ActivityStackSupervisor.java:2569) 
                                           at com.android.server.am.ActivityStackSupervisor.startActivityMayWait(ActivityStackSupervisor.java:2039) 
                                           at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5851) 
                                           at com.android.server.am.ActivityManagerService.startActivity(ActivityManagerService.java:5629) 
                                           at android.app.ActivityManagerNative.onTransact(ActivityManagerNative.java:146) 
                                           at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3723) 
                                           at android.os.Binder.execTransact(Binder.java:446) 
                                       	Suppressed: java.lang.ClassNotFoundException: com.theartofdev.edmodo.cropper.CropImageOptions
                                           at java.lang.Class.classForName(Native Method)
                                           at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                           at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                           at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                           		... 18 more
                                        Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by ArthurHub** [comment]
Same as #329, fix in next version, soon.
