### ISSUE TITLE
Getting error pickImageResult.jpeg: open failed: ENOENT (No such file or directory)

### ISSUE THREAD

**Issue by somghosh** [ArthurHub/Android-Image-Cropper#32]
Hello, I have been getting an error/crash using the library

Crash is : 
	
	pickImageResult.jpeg: open failed: ENOENT (No such file or directory)

and is caused in the following lines:

	at com.theartofdev.edmodo.cropper.util.ImageViewUtil.decodeSampledBitmap(ImageViewUtil.java:156)
	at com.theartofdev.edmodo.cropper.CropImageView.setImageUri(CropImageView.java:290)
	at com.gmspartnersltd.earthmiles.views.ActivityImageCrop.onCreate(ActivityImageCrop.java:51)
	

Is there a solution for this? I am using : compile 'com.theartofdev.edmodo:android-image-cropper:1.0.3'

	
	
## Stacktrace is as below

	java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gmspartnersltd.earthmiles/com.gmspartnersltd.earthmiles.views.ActivityImageCrop}: java.lang.RuntimeException: Failed to load sampled bitmap
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3149)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3248)
	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6872)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
	Caused by: java.lang.RuntimeException: Failed to load sampled bitmap
	at com.theartofdev.edmodo.cropper.util.ImageViewUtil.decodeSampledBitmap(ImageViewUtil.java:156)
	at com.theartofdev.edmodo.cropper.CropImageView.setImageUri(CropImageView.java:290)
	at com.gmspartnersltd.earthmiles.views.ActivityImageCrop.onCreate(ActivityImageCrop.java:51)
	at android.app.Activity.performCreate(Activity.java:6550)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
	... 10 more
	Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.gmspartnersltd.earthmiles/cache/pickImageResult.jpeg: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at java.io.FileInputStream.<init>(FileInputStream.java:103)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:693)
	at com.theartofdev.edmodo.cropper.util.ImageViewUtil.decodeSampledBitmap(ImageViewUtil.java:137)
	... 15 more
	Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	... 19 more
	java.lang.RuntimeException: Failed to load sampled bitmap
	at com.theartofdev.edmodo.cropper.util.ImageViewUtil.decodeSampledBitmap(ImageViewUtil.java:156)
	at com.theartofdev.edmodo.cropper.CropImageView.setImageUri(CropImageView.java:290)
	at com.gmspartnersltd.earthmiles.views.ActivityImageCrop.onCreate(ActivityImageCrop.java:51)
	at android.app.Activity.performCreate(Activity.java:6550)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3248)
	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6872)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
	Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.gmspartnersltd.earthmiles/cache/pickImageResult.jpeg: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at java.io.FileInputStream.<init>(FileInputStream.java:103)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:693)
	at com.theartofdev.edmodo.cropper.util.ImageViewUtil.decodeSampledBitmap(ImageViewUtil.java:137)
	... 15 more
	Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	... 19 more
	java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.gmspartnersltd.earthmiles/cache/pickImageResult.jpeg: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at java.io.FileInputStream.<init>(FileInputStream.java:103)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:693)
	at com.theartofdev.edmodo.cropper.util.ImageViewUtil.decodeSampledBitmap(ImageViewUtil.java:137)
	at com.theartofdev.edmodo.cropper.CropImageView.setImageUri(CropImageView.java:290)
	at com.gmspartnersltd.earthmiles.views.ActivityImageCrop.onCreate(ActivityImageCrop.java:51)
	at android.app.Activity.performCreate(Activity.java:6550)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3248)
	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6872)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
	Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	... 19 more
	android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at java.io.FileInputStream.<init>(FileInputStream.java:103)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:693)
	at com.theartofdev.edmodo.cropper.util.ImageViewUtil.decodeSampledBitmap(ImageViewUtil.java:137)
	at com.theartofdev.edmodo.cropper.CropImageView.setImageUri(CropImageView.java:290)
	at com.gmspartnersltd.earthmiles.views.ActivityImageCrop.onCreate(ActivityImageCrop.java:51)
	at android.app.Activity.performCreate(Activity.java:6550)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3248)
	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6872)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4033)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1720)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6837)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
	at io.realm.internal.UncheckedRow.nativeGetString(Native Method)
	at io.realm.internal.UncheckedRow.getString(UncheckedRow.java:169)
	at io.realm.RewardRealmProxy.getCategory(RewardRealmProxy.java:398)
	at com.gmspartnersltd.earthmiles.globalstate.App.getRewardsByCategory(App.java:2227)
	at com.gmspartnersltd.earthmiles.views.mainthreetabs.rewardsfragment.RewardsSubFragment.getNewPojoListToFill(RewardsSubFragment.java:127)
	at com.gmspartnersltd.earthmiles.views.mainthreetabs.BaseListFragment.onPostNetworkRequestWithCode(BaseListFragment.java:363)
	at com.gmspartnersltd.earthmiles.views.mainthreetabs.rewardsfragment.RewardsSubFragment.onResume(RewardsSubFragment.java:171)
	at android.app.Fragment.performResume(Fragment.java:2162)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:943)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1082)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1064)
	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1894)
	at android.app.Fragment.performResume(Fragment.java:2168)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:943)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1082)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1064)
	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1894)
	at android.app.Activity.performResume(Activity.java:6636)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3991)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:943)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1082)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1064)
	at android.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1894)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3248)
	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6872)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
	at com.theartofdev.edmodo.cropper.util.ImageViewUtil.decodeSampledBitmap(ImageViewUtil.java:156)
	at com.theartofdev.edmodo.cropper.CropImageView.setImageUri(CropImageView.java:290)
	at com.gmspartnersltd.earthmiles.views.ActivityImageCrop.onCreate(ActivityImageCrop.java:51)
	at android.app.Activity.performCreate(Activity.java:6550)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
	Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/com.gmspartnersltd.earthmiles/cache/pickImageResult.jpeg: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at java.io.FileInputStream.<init>(FileInputStream.java:103)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:693)
	at com.theartofdev.edmodo.cropper.util.ImageViewUtil.decodeSampledBitmap(ImageViewUtil.java:137)
	... 15 more
	Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	... 19 more
	at com.theartofdev.edmodo.cropper.CropImageView.setImageUri(CropImageView.java:290)
	at com.gmspartnersltd.earthmiles.views.ActivityImageCrop.onCreate(ActivityImageCrop.java:51)
	at android.app.Activity.performCreate(Activity.java:6550)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3248)
	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6872)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at java.io.FileInputStream.<init>(FileInputStream.java:103)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:693)
	at com.theartofdev.edmodo.cropper.util.ImageViewUtil.decodeSampledBitmap(ImageViewUtil.java:137)
	Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)
	... 19 more
	at java.io.FileInputStream.<init>(FileInputStream.java:76)
	at java.io.FileInputStream.<init>(FileInputStream.java:103)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:693)
	at com.theartofdev.edmodo.cropper.util.ImageViewUtil.decodeSampledBitmap(ImageViewUtil.java:137)
	at com.theartofdev.edmodo.cropper.CropImageView.setImageUri(CropImageView.java:290)
	at com.gmspartnersltd.earthmiles.views.ActivityImageCrop.onCreate(ActivityImageCrop.java:51)
	at android.app.Activity.performCreate(Activity.java:6550)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1120)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3248)
	at android.app.ActivityThread.access$1000(ActivityThread.java:197)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1681)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6872)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
	at libcore.io.Posix.open(Native Method)
	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
	at libcore.io.IoBridge.open(IoBridge.java:442)

**Comment by ArthurHub** [comment]
It looks like the file cannot be found, assuming you are using [my sample gist](https://gist.github.com/ArthurHub/8a8530dd688df409fb20) to select image to crop
 * what is the source you selected, is it camera, non default camera app?
 * what android version / device you are using?

regardless you should always handle exceptions from third-party code in your activity to provide graceful error handling, the library cannot handle it for you.

**Comment by CapnSpellcheck** [comment]
FWIW, I developed my own image picking/cropping solution. I occasionally see this same exception, mostly when the user picked an image from an app using an ACTION_GET_CONTENT image intent, but I just saw it once when user used camera. I show an error in the app saying that the image couldn't be accessed.
