### ISSUE TITLE
NullPointerException in startCropWorkerTask

### ISSUE THREAD

**Issue by krupalagile** [ArthurHub/Android-Image-Cropper#356]
Device: Sony Z2
OS Version : Android 6.0.1
Stack Trace : 
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                            at com.theartofdev.edmodo.cropper.CropImageView.startCropWorkerTask(CropImageView.java:923)
                                                                            at com.theartofdev.edmodo.cropper.CropImageView.saveCroppedImageAsync(CropImageView.java:648)
                                                                            at com.theartofdev.edmodo.cropper.CropImageActivity.cropImage(CropImageActivity.java:164)
                                                                            at com.theartofdev.edmodo.cropper.CropImageActivity.onOptionsItemSelected(CropImageActivity.java:115)
                                                                            at android.app.Activity.onMenuItemSelected(Activity.java:2948)
                                                                            at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:403)
                                                                            at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:179)
                                                                            at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:100)
                                                                            at android.support.v7.app.AppCompatDelegateImplV7.onMenuItemSelected(AppCompatDelegateImplV7.java:655)
                                                                            at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)
                                                                            at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
                                                                            at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)
                                                                            at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)
                                                                            at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:618)
                                                                            at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:139)
                                                                            at android.view.View.performClick(View.java:5280)
                                                                            at android.view.View$PerformClick.run(View.java:21239)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:224)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5526)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by sungyun-lim** [comment]
metoo........

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
                                                                            at com.theartofdev.edmodo.cropper.CropImageView.getWholeImageRect(CropImageView.java:625)
                                                                            at com.theartofdev.edmodo.cropper.CropImageActivity.getResultIntent(CropImageActivity.java:322)
                                                                            at com.theartofdev.edmodo.cropper.CropImageActivity.setResult(CropImageActivity.java:299)
                                                                            at com.theartofdev.edmodo.cropper.CropImageActivity.onSetImageUriComplete(CropImageActivity.java:241)
                                                                            at com.theartofdev.edmodo.cropper.CropImageView.onSetImageUriAsyncComplete(CropImageView.java:1067)
                                                                            at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute(BitmapLoadingWorkerTask.java:116)
                                                                            at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute(BitmapLoadingWorkerTask.java:26)
                                                                            at android.os.AsyncTask.finish(AsyncTask.java:667)
                                                                            at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:154)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by ArthurHub** [comment]
update to v2.5.0, let me know if you still experience this

**Comment by AndroidDeveloperLB** [comment]
@ArthurHub Actually I have this too, and reported here:
https://github.com/ArthurHub/Android-Image-Cropper/issues/502
And I use version 2.6.0...
