### ISSUE TITLE
NullPointerException @ CropImageActivity.onCreate

### ISSUE THREAD

**Issue by gilshallem** [ArthurHub/Android-Image-Cropper#371]
Hi, I get this exception..
I can not recreate it because it is taken from a crashlytics. on my own device it works fine.

Please help! :)

```
  if (imageFiles.size()>0) {
                    CropImage.activity(Uri.fromFile(imageFiles.get(0)))
                            .setGuidelines(CropImageView.Guidelines.ON)
                            .setAspectRatio(1,1)
                            .setCropShape(CropImageView.CropShape.OVAL)
                            .setRequestedSize(128,128)
                            .start(getContext(),this);

                }
```

> Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.gilapps.smsshare2/com.theartofdev.edmodo.cropper.CropImageActivity}: java.lang.NullPointerException
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
>        at android.app.ActivityThread.access$600(ActivityThread.java:141)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loop(Looper.java:137)
>        at android.app.ActivityThread.main(ActivityThread.java:5103)
>        at java.lang.reflect.Method.invokeNative(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:525)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
>        at dalvik.system.NativeStart.main(NativeStart.java)
> Caused by java.lang.NullPointerException
>        at com.theartofdev.edmodo.cropper.CropImageActivity.onCreate(CropImageActivity.java:68)
>        at android.app.Activity.performCreate(Activity.java:5133)
>        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
>        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
>        at android.app.ActivityThread.access$600(ActivityThread.java:141)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
>        at android.os.Handler.dispatchMessage(Handler.java:99)
>        at android.os.Looper.loop(Looper.java:137)
>        at android.app.ActivityThread.main(ActivityThread.java:5103)
>        at java.lang.reflect.Method.invokeNative(Method.java)
>        at java.lang.reflect.Method.invoke(Method.java:525)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
>        at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by falkontre** [comment]
I have a similar issue (taken from crashlytics),

There is no check for image nullability.

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at com.theartofdev.edmodo.cropper.CropImageView.getWholeImageRect(CropImageView.java:625)
       at com.theartofdev.edmodo.cropper.CropImageActivity.getResultIntent(CropImageActivity.java:322)
       at com.theartofdev.edmodo.cropper.CropImageActivity.setResult(CropImageActivity.java:299)
       at com.theartofdev.edmodo.cropper.CropImageActivity.onSetImageUriComplete(CropImageActivity.java:241)
       at com.theartofdev.edmodo.cropper.CropImageView.onSetImageUriAsyncComplete(CropImageView.java:1067)
       at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute(BitmapLoadingWorkerTask.java:116)
       at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute(BitmapLoadingWorkerTask.java:26)
       at android.os.AsyncTask.finish(AsyncTask.java:679)
       at android.os.AsyncTask.access$500(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:696)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:150)
       at android.app.ActivityThread.main(ActivityThread.java:5621)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)

**Comment by ArthurHub** [comment]
update to v2.5.0, let me know if you still experience this

**Comment by FitApps7** [comment]
On v2.6.0, again give same error 
unable to start CropImageActivity.java

CropImageActivity.java line 63
com.theartofdev.edmodo.cropper.CropImageActivity.onCreate





Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{frame3d.text3d.name/com.theartofdev.edmodo.cropper.CropImageActivity}: java.lang.NullPointerExceptio






Caused by java.lang.NullPointerException
       at com.theartofdev.edmodo.cropper.CropImageActivity.onCreate(CropImageActivity.java:63)
       at android.app.Activity.performCreate(Activity.java:5133)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2175)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5103)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)




Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{frame3d.text3d.name/com.theartofdev.edmodo.cropper.CropImageActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
       at android.app.ActivityThread.access$600(ActivityThread.java:141)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.app.ActivityThread.main(ActivityThread.java:5103)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:525)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
       at dalvik.system.NativeStart.main(NativeStart.java)



on Defy mini Device, running OS 4.3.1

**Comment by kpradeepkumarreddy** [comment]
I'm also facing the same issue in version 2.6.0, here is the crash report from Crashlytics :-

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lxltech.sc.participant/com.theartofdev.edmodo.cropper.CropImageActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
       at com.theartofdev.edmodo.cropper.CropImageActivity.onCreate(CropImageActivity.java:63)
       at android.app.Activity.performCreate(Activity.java:6280)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5420)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by mianaliasjad** [comment]
Same as @kpradeepkumarreddy on version 2.7+ with Nexus 4 Android 6.0 device.
Any solution?

**Comment by Pro-55** [comment]
Is this issue fixed in latest version?

**Comment by samigehi** [comment]
Having same issue on nexus 4 device, 
`Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)'  on com.theartofdev.edmodo.cropper.CropImageActivity.onCreate
`
