### ISSUE TITLE
NullPointerExpection android.graphics.Bitmap.getWidth()

### ISSUE THREAD

**Issue by atuldhanuka1990** [ArthurHub/Android-Image-Cropper#415]
Hi,

I am getting the NullPointerException  after selecting  Picture from the gallery

    `private void selectImage() {
                CropImage.activity(null)
                    .setGuidelines(CropImageView.Guidelines.ON)
                    .setActivityTitle("Photo Crop")
                    .setCropShape(CropImageView.CropShape.OVAL)
                    .setRequestedSize(400, 400)
                    .start(getContext(), this);
     }`

    compileSdkVersion 25
    buildToolsVersion "25.0.1"
    defaultConfig {
        applicationId "com.example.activity"
        minSdkVersion 21
        targetSdkVersion 21
        multiDexEnabled true
    }

    dependencies {
           compile "com.android.support:appcompat-v7:25.3.1"
           compile "com.android.support:design:25.3.1"
           compile 'com.theartofdev.edmodo:android-image-cropper:2.4.+'
    }

OS Version: 6.0.1
Device: Galaxy S6
RAM Free: 30.4%
Disk Free: 71.3%

Logcat:-

> Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
       at com.theartofdev.edmodo.cropper.CropImageView.getWholeImageRect(CropImageView.java:625)
       at com.theartofdev.edmodo.cropper.CropImageActivity.getResultIntent(CropImageActivity.java:322)
       at com.theartofdev.edmodo.cropper.CropImageActivity.setResult(CropImageActivity.java:299)
       at com.theartofdev.edmodo.cropper.CropImageActivity.onSetImageUriComplete(CropImageActivity.java:241)
       at com.theartofdev.edmodo.cropper.CropImageView.onSetImageUriAsyncComplete(CropImageView.java:1067)
       at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute(BitmapLoadingWorkerTask.java:116)
       at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute(BitmapLoadingWorkerTask.java:26)
       at android.os.AsyncTask.finish(AsyncTask.java:651)
       at android.os.AsyncTask.access$500(AsyncTask.java:180)
       at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7229)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ArthurHub** [comment]
fixed in v2.5

**Comment by atuldhanuka1990** [comment]
Thank you

**Comment by imrananeuronsolutions** [comment]
Not working for me, It just selected images from gallery and not giviing proper image , so image can be show on my image view
please reply asap
