### ISSUE TITLE
Bug: on API 16 emulator, we have "Unsupported action" in "select source" dialog

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ArthurHub/Android-Image-Cropper#423]
In the sample "sample", we have this:
![image](https://user-images.githubusercontent.com/5357526/31607834-a33c9f5a-b276-11e7-8c41-b9de750168e2.png)

Pressing on this weird item, I get this:

![image](https://user-images.githubusercontent.com/5357526/31607837-aec09160-b276-11e7-8451-dfabb8b899e8.png)

**Comment by ArthurHub** [comment]
why is this important?

**Comment by AndroidDeveloperLB** [comment]
What is it? Is it important? Does it occur on real devices?
Why does it get shown? Is it possible to avoid this?

**Comment by ArthurHub** [comment]
Sure.. Feel free to debug android sdk

**Comment by AndroidDeveloperLB** [comment]
I don't understand the answer.
What is this item? I never saw it.

**Comment by ArthurHub** [comment]
https://en.m.wikipedia.org/wiki/Android_software_development

**Comment by AndroidDeveloperLB** [comment]
I don't see an answer to those questions on the link you've provided.
Where exactly do you see it there?

**Comment by ArthurHub** [comment]
You have a problem with Android internals, you need to debug android code for that. SDK is how you do that.

**Comment by AndroidDeveloperLB** [comment]
The sample causes a dialog of sharing that has an item that is not supposed to be shown. It doesn't get shown on real devices.

**Comment by AndroidDeveloperLB** [comment]
Or at least I can't reproduce it.
In any case, this is not related to Android, because otherwise it would have existed on devices too.

**Comment by ArthurHub** [comment]
Debug the code!

**Comment by AndroidDeveloperLB** [comment]
That's a very different answer from saying I should debug Android SDK. 
Debugging the code proves that the code has an issue.
Anyway, after doing so, I've found this :
1. The sample can crash in case I close the dialog by clicking outside of the dialog, and in fact even when I choose the other options (camera/gallery) . Here's the log:

10-20 22:24:14.613 1764-1764/com.example.croppersample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                         android.app.SuperNotCalledException: Activity {android/com.android.internal.app.ChooserActivity} did not call through to super.onStop()
                                                                             at android.app.Activity.performStop(Activity.java:4606)
                                                                             at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3071)
                                                                             at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3130)
                                                                             at android.app.ActivityThread.access$1200(ActivityThread.java:123)
                                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1180)
                                                                             at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                             at android.os.Looper.loop(Looper.java:137)
                                                                             at android.app.ActivityThread.main(ActivityThread.java:4424)
                                                                             at java.lang.reflect.Method.invokeNative(Native Method)
                                                                             at java.lang.reflect.Method.invoke(Method.java:511)
                                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
                                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
                                                                             at dalvik.system.NativeStart.main(Native Method)

Tested on API 15 emulator.
Weird thing is that the code of the sample doesn't seem to have a code that should cause this. And the log seem to refer to Android's own code.
Any clue why this occurs, and how to fix it?

2. The extra intent that is added is this:

Intent { act=android.intent.action.GET_CONTENT typ=image/* pkg=com.android.fallback cmp=com.android.fallback/.Fallback }

Searching on the Internet, I don't see it being mentioned together (I searched for : ""com.android.fallback" ACTION_GET_CONTENT").

**Comment by AndroidDeveloperLB** [comment]
Seems Android API 24 also has the weird "Unsupported action" : 

![image](https://user-images.githubusercontent.com/5357526/31844361-db0a9c4c-b600-11e7-9e18-400a9be3e1c0.png)

**Comment by ArthurHub** [comment]
Looks like the issue is not in the library code, Try debuging Android ChooserActivity

**Comment by AndroidDeveloperLB** [comment]
Seems like an emulator-only issue, so I've reported this to Google:
https://issuetracker.google.com/issues/68073231
