### ISSUE TITLE
Having an Issue with Fragments(Read all the solutions)

### ISSUE THREAD

**Issue by moses-lee** [ArthurHub/Android-Image-Cropper#434]
I am trying to use the cropper from a fragment from a nav drawer. I have read all the solutions for the fragments, but they don't seem to be working. I'm getting the error:

     Failure delivering result ResultInfo{who=null, request=65541, result=-1, data=Intent

Here's the code:

    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
     super.onActivityResult(requestCode, resultCode, data);
        if(requestCode==GALLERY_REQUEST && resultCode==Activity.RESULT_OK&& data != null){
            Uri imageUri=data.getData();
            CropImage.activity(imageUri)
                    .setGuidelines(CropImageView.Guidelines.ON)
                    .setAspectRatio(1,1)
                    .setMinCropResultSize(200,200)
                    .setCropShape(CropImageView.CropShape.OVAL)
                    //error here
                    .start(getContext(), this);

        }

**Comment by ArthurHub** [comment]
stack trace?

**Comment by moses-lee** [comment]
Sorry about the late response, but here it is:

FATAL EXCEPTION: main
                                                                         \  Process: com.spotz2share.spotz, PID: 13188
                                                                       java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65541, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:10558 flg=0x1 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } }} to activity {com.spotz2share.spotz/com.spotz2share.spotz.MainActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.spotz2share.spotz/com.theartofdev.edmodo.cropper.CropImageActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                           at android.app.ActivityThread.deliverResults(ActivityThread.java:4491)
                                                                           at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534)
                                                                           at android.app.ActivityThread.-wrap22(ActivityThread.java)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6642)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                                        Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.spotz2share.spotz/com.theartofdev.edmodo.cropper.CropImageActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                           at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1815)
                                                                           at android.app.Instrumentation.execStartActivity(Instrumentation.java:1531)
                                                                           at android.app.Activity.startActivityForResult(Activity.java:4389)
                                                                           at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                           at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:30)
                                                                           at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:146)
                                                                           at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:937)
                                                                           at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1047)
                                                                           at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:959)
                                                                           at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:948)
                                                                           at com.theartofdev.edmodo.cropper.CropImage$ActivityBuilder.start(CropImage.java:490)
                                                                           at com.spotz2share.spotz.nav_fragments.SettingsFragment.onActivityResult(SettingsFragment.java:153)
                                                                           at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
                                                                           at android.app.Activity.dispatchActivityResult(Activity.java:7226)
                                                                           at android.app.ActivityThread.deliverResults(ActivityThread.java:4487)
                                                                           at android.app.ActivityThread.handleSendResult(ActivityThread.java:4534) 
                                                                           at android.app.ActivityThread.-wrap22(ActivityThread.java) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1699) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                           at android.os.Looper.loop(Looper.java:154) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6642) 
                                                                           at java.lang.reflect.Method.invoke(Native Method) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by moses-lee** [comment]
Nevermind, got it
