### ISSUE TITLE
Failure delivering result

### ISSUE THREAD

**Issue by hitesh-bhaliya** [ArthurHub/Android-Image-Cropper#445]
Bitmap cropBitmap = ivsetcacheImg.getDrawingCache();

                                CropImage.activity(general.getImageUri(this, cropBitmap))
                                        .setGuidelines(CropImageView.Guidelines.ON)
                                        .setAspectRatio(1, 1)
                                        .setAutoZoomEnabled(false)
                                        .setRotationDegrees(30)
                                        .setAllowCounterRotation(true)
                                        .start(this);

stack trace >

Fatal Exception: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=203, result=204, data=Intent {  launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 }(has extras) }} to activity {com.Jewelxy.B2BJewelry/com.Jewelxy.B2BJewelry.activity.profile.ActivityProfileEditUser}: java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4472)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515)
       at android.app.ActivityThread.-wrap22(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)
Caused by java.lang.NullPointerException: Attempt to invoke a virtual method on a null object reference
       at com.Jewelxy.B2BJewelry.activity.profile.ActivityProfileEditUser.onActivityResult(Unknown Source)
       at android.app.Activity.dispatchActivityResult(Activity.java:7256)
       at android.app.ActivityThread.deliverResults(ActivityThread.java:4468)
       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4515)
       at android.app.ActivityThread.-wrap22(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1687)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6682)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

**Comment by hitesh-bhaliya** [comment]
on activity result 
          if (resultCode == RESULT_OK) {

                    if (data != null) {
                        CropImage.ActivityResult result = CropImage.getActivityResult(data);
                     
                      if (result != null) {
                            Uri uri = result.getUri();
                         }

                       }
             }

**Comment by HaghighatDoost** [comment]
@hitesh-bhaliya did you fix it? i have this issue too

**Comment by pondkub** [comment]
I have this problem too, (resultCode = 204) right after I add .setOutputUri()
