### ISSUE TITLE
Failed to load sampled bitmap

### ISSUE THREAD

**Issue by pedronveloso** [ArthurHub/Android-Image-Cropper#47]
I'm getting some reports of user's that are unable to set a photo, and have this log message:

`Fatal Exception: java.lang.RuntimeException: Failed to load sampled bitmap
       at com.theartofdev.edmodo.cropper.BitmapUtils.decodeSampledBitmapRegion(BitmapUtils.java:178)
       at com.theartofdev.edmodo.cropper.BitmapUtils.cropBitmap(BitmapUtils.java:191)
       at com.theartofdev.edmodo.cropper.CropImageView.getCroppedImage(CropImageView.java:456)
       at com.rogertalk.roger.ui.screens.ImageCropActivity.cropImagePressed(ImageCropActivity.kt:99)
       at com.rogertalk.roger.ui.screens.ImageCropActivity.access$cropImagePressed(ImageCropActivity.kt:28)
       at com.rogertalk.roger.ui.screens.ImageCropActivity$setupUI$1.onClick(ImageCropActivity.kt:74)
       at android.view.View.performClick(View.java:4856)
       at android.view.View$PerformClick.run(View.java:19956)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5373)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)
Caused by java.io.IOException: Image failed to decode using JPEG decoder
       at android.graphics.BitmapRegionDecoder.nativeNewInstance(BitmapRegionDecoder.java)
       at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
       at com.theartofdev.edmodo.cropper.BitmapUtils.decodeSampledBitmapRegion(BitmapUtils.java:172)
       at com.theartofdev.edmodo.cropper.BitmapUtils.cropBitmap(BitmapUtils.java:191)
       at com.theartofdev.edmodo.cropper.CropImageView.getCroppedImage(CropImageView.java:456)
       at com.rogertalk.roger.ui.screens.ImageCropActivity.cropImagePressed(ImageCropActivity.kt:99)
       at com.rogertalk.roger.ui.screens.ImageCropActivity.access$cropImagePressed(ImageCropActivity.kt:28)
       at com.rogertalk.roger.ui.screens.ImageCropActivity$setupUI$1.onClick(ImageCropActivity.kt:74)
       at android.view.View.performClick(View.java:4856)
       at android.view.View$PerformClick.run(View.java:19956)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:211)
       at android.app.ActivityThread.main(ActivityThread.java:5373)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1020)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:815)`

It is happening on Android 5.0 and 5.1.1 so far. I myself cannot reproduce it, but know that this is making the app crash for those specific users. Any idea on what might be wrong?

**Comment by ArthurHub** [comment]
wow, looks like it's a bug in Android library :rage: 
Apparently Android bitmap decoding code is based on `Skia` library that has known bugs, mostly in `BitmapRegionDecoder` for specific features and formats.
I will a fallback to `BitmapFactory` full image decoding and then crop the required region in case `BitmapRegionDecoder` has failed.

Thank you for reporting this.

p.s. you should always catch exceptions to prevent app crash, show some error message, it is proffered user experience.

**Comment by ArthurHub** [comment]
added fallback to **v1.2.4**, let me know if there is still issue

**Comment by pedronveloso** [comment]
Thank you for the quick update :+1: and the awesome work on this library ;)

**Comment by lingboo** [comment]
I have the issue be like this: java.lang.RuntimeException: Failed to load sampled bitmap: file:///storage/emulated/0/MyDir/img_1463316925324.jpg

**Comment by kbajpai** [comment]
The issue still exists with v2.2.2 when passing URI - http://<hostname>/images/imagePath.jpeg

**Comment by ArthurHub** [comment]
External URI's (http) are not supported, only URI's to internal Android sources.

**Comment by satti8893** [comment]
is this solved? im having the same issue using latest build

**Comment by abhaymaniyar** [comment]
Hello @ArthurHub ! I also am this issue even when I am using an internal URI.

**Comment by deepakbajpay** [comment]
I am still facing same issue in V 2.7.0.

**Comment by andreififiita** [comment]
Same here, i am having this issue when trying to set the same Uri twice, when choosing image with Google Photos or in emulator with Files

**Comment by prabhakar612** [comment]
what is the solution for this issue, I'm still facing this issue.

**Comment by igniushka** [comment]
I found that adding 
`requestLegacyExternalStorage="true"`
to the manifest fixes the issue.

**Comment by Abdalnassir** [comment]
The issue is coming back again in Android 11 (SDK 30) and seems to affect mostly Samsung phones and Google pixel 3. Non of the above solutions worked! any tips? I am trying to solve for a week now but nothing so far.

**Comment by raimondo** [comment]
The issue is coming back again in Android 11 (SDK 30) and seems to affect mostly Samsung phones and Google pixel 3. Non of the above solutions worked! any tips? I am trying to solve for a week now but nothing so far.

**Comment by manojkumar1412** [comment]
Facing this again in Android 11(SDK 30), similar to reported in https://github.com/ArthurHub/Android-Image-Cropper/issues/47#issuecomment-880879472

**Comment by rajeshvexil** [comment]
I am also facing android 11, 12(sdk 30, 31,32) when image is captured by camera then crop option not coming throw-out exception.
