### ISSUE TITLE
Crashes if intent chooser is cancelled by user (kotlin)

### ISSUE THREAD

**Issue by musikeroll** [ArthurHub/Android-Image-Cropper#492]
Hi,

```
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=203, result=0, data=null} to activity {com.example.app.debug/com.example.app.view.MainActivity}:
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
      at android.app.ActivityThread.deliverResults(ActivityThread.java:4481)
      at android.app.ActivityThread.handleSendResult(ActivityThread.java:4524)
      at android.app.ActivityThread.-wrap22(ActivityThread.java)
      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1691)
      at android.os.Handler.dispatchMessage(Handler.java:102)
      at android.os.Looper.loop(Looper.java:154)
      at android.app.ActivityThread.main(ActivityThread.java:6692)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
      at com.example.app.view.MainActivity.onActivityResult(MainActivity.kt:0)
      at android.app.Activity.dispatchActivityResult(Activity.java:7226)
```

android image cropper: 2.6.0
kotlin version: 1.2.21
compile SDK: 27
min SDK: 22

**Comment by musikeroll** [comment]
Sorry it was my error.. issue was fix after changing my method signature from:

`override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent)`

to

`override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?)`
