### ISSUE TITLE
ActivityNotFound exception

### ISSUE THREAD

**Issue by kshitiz1007** [ArthurHub/Android-Image-Cropper#508]
Hi there, 
I am working on api 26..

compileSdkVersion 26
 buildToolsVersion "27.0.3",

My gradle build is -- classpath 'com.android.tools.build:gradle:2.3.2'

I am using this this library ---  
    compile 'com.theartofdev.edmodo:android-image-cropper:2.5.+'

MY ERROR IS ------->  
      Unable to find explicit activity class 
      {com.example.singhkshitiz.letschat/com.theartofdev.edmodo.cropper.CropImageActivity}; have you 
      declared this activity in your AndroidManifest.xml?

Someone  Please help...

My gradle(app) file is --->

apply plugin: 'com.android.application'
android {
    compileSdkVersion 26
    buildToolsVersion "27.0.3"
    defaultConfig {
        applicationId "com.example.singhkshitiz.letschat"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.google.firebase:firebase-auth:10.0.1'
    compile 'com.android.support:design:26.+'
    compile 'com.android.support:support-v4:26.+'
    compile 'de.hdodenhof:circleimageview:2.2.0'
    compile 'com.theartofdev.edmodo:android-image-cropper:2.5.+'

    compile 'com.google.firebase:firebase-database:10.0.1'
    testCompile 'junit:junit:4.12'
}
apply plugin: 'com.google.gms.google-services'

My manifest is --->

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.singhkshitiz.letschat">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>
        <activity android:name=".LoginActivity" />
        <activity android:name=".RegisterActivity" />
        <activity
            android:name=".SettingActivity"
            android:theme="@style/AppTheme2" />
        <activity android:name=".StatusActivity"></activity>
    </application>

    <activity android:name="com.theartofdev.edmodo.cropper.CropImageActivity" />

</manifest>

Complete Error is -->
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                   Process: com.example.singhkshitiz.letschat, PID: 28155
                                                                                   java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=1, result=-1, data=Intent { dat=content://com.android.providers.media.documents/document/image:164237 flg=0x1 }} to activity {com.example.singhkshitiz.letschat/com.example.singhkshitiz.letschat.SettingActivity}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.singhkshitiz.letschat/com.theartofdev.edmodo.cropper.CropImageActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:3744)
                                                                                       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3787)
                                                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:153)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5529)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)
                                                                                    Caused by: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.example.singhkshitiz.letschat/com.theartofdev.edmodo.cropper.CropImageActivity}; have you declared this activity in your AndroidManifest.xml?
                                                                                       at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1801)
                                                                                       at android.app.Instrumentation.execStartActivity(Instrumentation.java:1514)
                                                                                       at android.app.Activity.startActivityForResult(Activity.java:3978)
                                                                                       at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:54)
                                                                                       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:75)
                                                                                       at android.app.Activity.startActivityForResult(Activity.java:3939)
                                                                                       at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:708)
                                                                                       at com.theartofdev.edmodo.cropper.CropImage$ActivityBuilder.start(CropImage.java:486)
                                                                                       at com.example.singhkshitiz.letschat.SettingActivity.onActivityResult(SettingActivity.java:103)
                                                                                       at android.app.Activity.dispatchActivityResult(Activity.java:6508)
                                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:3740)
                                                                                       at android.app.ActivityThread.handleSendResult(ActivityThread.java:3787) 
                                                                                       at android.app.ActivityThread.access$1500(ActivityThread.java:153) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1424) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:5529) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

**Comment by kshitiz1007** [comment]
Sorry, I clenaed my project and it worked
