### ISSUE TITLE
NullPointerException in CropImageActivity in version 2.6.0 

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [ArthurHub/Android-Image-Cropper#551]
Creating a new issue as the existing issue(371) was closed quoting fixed in version 2.5.0. 
I'm using Version 2.6.0, here is the crash report from Crashlytics :-

Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.lxltech.sc.participant/com.theartofdev.edmodo.cropper.CropImageActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5420)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
at com.theartofdev.edmodo.cropper.CropImageActivity.onCreate(CropImageActivity.java:63)
at android.app.Activity.performCreate(Activity.java:6280)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2372)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
at android.app.ActivityThread.-wrap11(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5420)
at java.lang.reflect.Method.invoke(Method.java)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by tomerpetel** [comment]
Same here... @kpradeepkumarreddy did you find a solution/workaround?

**Comment by kpradeepkumarreddy** [comment]
workaround is to use some other library like [https://github.com/nguyenhoanglam/ImagePicker]

**Comment by tomerpetel** [comment]
@kpradeepkumarreddy  that's a big workaround :)
