### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by allen1988** [ArthurHub/Android-Image-Cropper#560]
this is error:
java.lang.NullPointerException: Attempt to read from field 'int android.graphics.Bitmap$Config.nativeInt' on a null object reference
	at android.graphics.Bitmap.copy(Bitmap.java:583)
	at com.theartofdev.edmodo.cropper.BitmapUtils.cropBitmapObjectWithScale(BitmapUtils.java:215)
	at com.theartofdev.edmodo.cropper.BitmapUtils.cropBitmapObjectHandleOOM(BitmapUtils.java:155)
	at com.theartofdev.edmodo.cropper.CropImageView.getCroppedImage(CropImageView.java:790)
	at com.theartofdev.edmodo.cropper.CropImageView.getCroppedImage(CropImageView.java:737)
	at com.duowan.makefriends.photo.BasePhotoActivity.completeCrop(BasePhotoActivity.java:132)
	at com.duowan.makefriends.photo.BasePhotoActivity.access$100(BasePhotoActivity.java:25)
	at com.duowan.makefriends.photo.BasePhotoActivity$2.onClick(BasePhotoActivity.java:121)
	at android.view.View.performClick(View.java:5231)
	at android.view.View$PerformClick.run(View.java:21240)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:179)
	at android.app.ActivityThread.main(ActivityThread.java:5769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)

and my code is:
 <com.theartofdev.edmodo.cropper.CropImageView
            android:id="@+id/civ_preview"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />

cropImageView.setVisibility(View.VISIBLE);
                cropImageView.setImageBitmap(result);
                cropImageView.setAspectRatio(1, 1);
                cropImageView.setFixedAspectRatio(true);
                if (photoController.getRotate() > 0) {
                    cropImageView.rotateImage(photoController.getRotate());
                }

**Comment by hoangcongtuan** [comment]
i still waiting for solution :(

**Comment by zhaodexi** [comment]
I hava the same problem...
