### ISSUE TITLE
croped image not uploading with retrofit 2.0 

### ISSUE THREAD

**Issue by ahmedbilalsolexp** [ArthurHub/Android-Image-Cropper#585]
Process: com.solexp.mandionline, PID: 23055
                                                                        java.lang.NullPointerException: Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
                                                                            at java.util.regex.Matcher.reset(Matcher.java:177)
                                                                            at java.util.regex.Matcher.<init>(Matcher.java:90)
                                                                            at java.util.regex.Pattern.matcher(Pattern.java:297)
                                                                            at okhttp3.MediaType.parse(MediaType.java:51)
                                                                            at com.solexp.mandionline.activities.ProfileActivity.uploadFile(ProfileActivity.java:594)
                                                                            at com.solexp.mandionline.activities.ProfileActivity.access$200(ProfileActivity.java:87)
                                                                            at com.solexp.mandionline.activities.ProfileActivity$7.onClick(ProfileActivity.java:313)
                                                                            at com.ontbee.legacyforks.cn.pedant.SweetAlert.SweetAlertDialog.onClick(SweetAlertDialog.java:373)
                                                                            at android.view.View.performClick(View.java:5197)
                                                                            at android.view.View$PerformClick.run(View.java:20926)
                                                                            at android.os.Handler.handleCallback(Handler.java:739)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                            at android.os.Looper.loop(Looper.java:145)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at java.lang.reflect.Method.invoke(Method.java:372)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

**Comment by arunavo4** [comment]
@ahmedbilalsolexp You need to upload it as a multipart file 
follow this tutorial on how to upload using retrofit
https://medium.com/@adinugroho/upload-image-from-android-app-using-retrofit-2-ae6f922b184c

**Comment by ahmedbilalsolexp** [comment]
i done this 6 moths ago thanks
