### ISSUE TITLE
NullPointerException in CropImageActivity

### ISSUE THREAD

**Issue by kagile** [ArthurHub/Android-Image-Cropper#616]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
       at com.theartofdev.edmodo.cropper.CropImageActivity.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6679)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

**Comment by emadPirayesh** [comment]
same issue in nexus6 
![crash](https://user-images.githubusercontent.com/25787919/75862843-c70b8800-5e14-11ea-9604-511b6bc3c871.png)
