### ISSUE TITLE
Got NullPointer Exception

### ISSUE THREAD

**Issue by gpandroid90** [ArthurHub/Android-Image-Cropper#636]
java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
	at com.theartofdev.edmodo.cropper.CropImageView.getWholeImageRect(CropImageView.java:625)
	at com.theartofdev.edmodo.cropper.CropImageActivity.getResultIntent(CropImageActivity.java:322)
	at com.theartofdev.edmodo.cropper.CropImageActivity.setResult(CropImageActivity.java:299)
	at com.theartofdev.edmodo.cropper.CropImageActivity.onSetImageUriComplete(CropImageActivity.java:241)
	at com.theartofdev.edmodo.cropper.CropImageView.onSetImageUriAsyncComplete(CropImageView.java:1067)
	at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute(BitmapLoadingWorkerTask.java:116)
	at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.onPostExecute(BitmapLoadingWorkerTask.java:26)
	at `android.os.AsyncTask.finish(AsyncTask.java:667)`
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:684)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6816)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1453)

**Comment by donfuxx** [comment]
what version did you use? That stacktrace certainly refers to an older version.
