### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by gitudrebel2013** [ArthurHub/Android-Image-Cropper#67]
I am using this awesome library in my application, but I sometimes get OutOfMemoryError

java.lang.RuntimeException: An error occured while executing doInBackground()
 at android.os.AsyncTask$3.done(AsyncTask.java:299)
 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
 at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
 at java.util.concurrent.FutureTask.run(FutureTask.java:239)
 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 at java.lang.Thread.run(Thread.java:856) Caused by: java.lang.OutOfMemoryError
 at android.graphics.Bitmap.nativeCreate(Native Method)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:718)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:695)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:628)
 at com.theartofdev.edmodo.cropper.BitmapUtils.rotateBitmapInt(BitmapUtils.java:378)
 at com.theartofdev.edmodo.cropper.BitmapUtils.cropBitmap(BitmapUtils.java:188)
 at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.doInBackground(BitmapCroppingWorkerTask.java:153)
 at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.doInBackground(BitmapCroppingWorkerTask.java:25)
 at android.os.AsyncTask$2.call(AsyncTask.java:287)
 at java.util.concurrent.FutureTask.run(FutureTask.java:234) ... 4 more java.lang.OutOfMemoryError
 at android.graphics.Bitmap.nativeCreate(Native Method)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:718)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:695)
 at android.graphics.Bitmap.createBitmap(Bitmap.java:628)
 at com.theartofdev.edmodo.cropper.BitmapUtils.rotateBitmapInt(BitmapUtils.java:378)
 at com.theartofdev.edmodo.cropper.BitmapUtils.cropBitmap(BitmapUtils.java:188)
 at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.doInBackground(BitmapCroppingWorkerTask.java:153)
 at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.doInBackground(BitmapCroppingWorkerTask.java:25)
 at android.os.AsyncTask$2.call(AsyncTask.java:287)
 at java.util.concurrent.FutureTask.run(FutureTask.java:234)
 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
 at java.lang.Thread.run(Thread.java:856)

**Comment by ArthurHub** [comment]
I believe you are not using the latest version.
If so please update, and let me know if the issue still exists.

**Comment by gitudrebel2013** [comment]
I have updated it, I will let you know if I get the error again . Thank you.

**Comment by pkirankmr** [comment]
I am still getting it...I am using the latest updated library 

java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.OutOfMemoryError: Failed to allocate a 24540476 byte allocation with 6407436 free bytes and 6MB until OOM
	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
	at android.graphics.Bitmap.nativeCreate(Native Method)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:946)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:917)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:848)
	at com.theartofdev.edmodo.cropper.BitmapUtils.rotateBitmapInt(BitmapUtils.java:433)
	at com.theartofdev.edmodo.cropper.BitmapUtils.cropBitmap(BitmapUtils.java:187)
	at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.doInBackground(BitmapCroppingWorkerTask.java:176)
	at com.theartofdev.edmodo.cropper.BitmapCroppingWorkerTask.doInBackground(BitmapCroppingWorkerTask.java:25)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by ArthurHub** [comment]
23 MB is a huge image, Android just can't handle it.
If you don't need a very large resolution image you can limit its size by providing required width/height parameters, the library will sample during decoding.
But if you want to preserve the high resolution you will have to crop it manually using native API or on the server side, you can get the crop rectangle and rotation to know what part to crop.

**Comment by pkirankmr** [comment]
The library is amazingly awesome...having tried many croppers, I loved it from the start..Thank you for all the efforts you put in

The image is actually 1mb but i dont know y android shows it as 23mb...I have restructed my code looking at your sample. Hopefully, it shouldn't come back

Once again, Thanks a lot

**Comment by ArthurHub** [comment]
Thank you.

The image is 1mb encoded, unfortunately Android "has to" decode it in memory which uses 4 bytes per pixel so this image has 6,135,119 pixels so the image resolution is around 2470x2470. That is a big image. 
There are ways to handle it but none of them are perfect, usually you don't need that height resolution so sampling is the best option, but every scenario is different.
