### ISSUE TITLE
Fail to load capturing image to crop 

### ISSUE THREAD

**Issue by lingboo** [ArthurHub/Android-Image-Cropper#73]
With gallery, everything is ok. But when i open camera to capture, I have the issue be like this: java.lang.RuntimeException: Failed to load sampled bitmap: file:///storage/emulated/0/MyDir/img_1463316925324.jpg. I'm using newest version

**Comment by ArthurHub** [comment]
Can you reproduce it in the sample app?
Can you post the full exception stack.

**Comment by lingboo** [comment]
D/Error: java.lang.RuntimeException: Failed to load sampled bitmap: file:///storage/emulated/0/MyDir/img_1463625998776.jpg.
I/dalvikvm: Could not find method android.content.Context.checkSelfPermission, referenced from method com.theartofdev.edmodo.cropper.CropImage.isReadExternalStoragePermissionsRequired.
But i'm still use permission ReadExternalStorage in Manifest ??

**Comment by ArthurHub** [comment]
Using marshmallow? see [Pick image for cropping from Camera or Gallery](https://github.com/ArthurHub/Android-Image-Cropper/wiki/Pick-image-for-cropping-from-Camera-or-Gallery)

**Comment by lingboo** [comment]
No, i'm using 4.4.2 (API 19). Any suggestion ?

**Comment by ArthurHub** [comment]
Can you reproduce it in the sample app?

**Comment by lingboo** [comment]
ye, here is my sample app: https://github.com/lingboo/CropImage

**Comment by ArthurHub** [comment]
Can't reproduce it on Nexus 5 (19), Moto X (23) or emulators...

So first change the exception log to `Log.d("Error", "failed", exception);` instead of `Log.d("Error",error.toString());` to get the full error.

Second try changing the camera output uri to:
```java
File file = new File(getExternalCacheDir() + File.separator + "MyDir" + File.separator);
```

P.S. Originally I meant if you can reproduce it in the sample app of the library.

**Comment by lingboo** [comment]
Your sample project a bit different with my project(i wanna as simple as possible):(
Full exception stack following: 
D/Error: failed
                                                            java.lang.RuntimeException: Failed to load sampled bitmap: file:///storage/emulated/0/Android/data/life.kiwi.cropimage/cache/MyDir/img_1463821262675.jpg
                                                                at com.theartofdev.edmodo.cropper.BitmapUtils.decodeSampledBitmap(BitmapUtils.java:130)
                                                                at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.doInBackground(BitmapLoadingWorkerTask.java:87)
                                                                at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.doInBackground(BitmapLoadingWorkerTask.java:26)
                                                                at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:841)
                                                             Caused by: java.io.FileNotFoundException: /storage/emulated/0/Android/data/life.kiwi.cropimage/cache/MyDir/img_1463821262675.jpg: open failed: ENOENT (No such file or directory)
                                                                at libcore.io.IoBridge.open(IoBridge.java:409)
                                                                at java.io.FileInputStream.<init>(FileInputStream.java:78)
                                                                at java.io.FileInputStream.<init>(FileInputStream.java:105)
                                                                at android.content.ContentResolver.openInputStream(ContentResolver.java:627)
                                                                at com.theartofdev.edmodo.cropper.BitmapUtils.decodeImageForOption(BitmapUtils.java:268)
                                                                at com.theartofdev.edmodo.cropper.BitmapUtils.decodeSampledBitmap(BitmapUtils.java:117)
                                                                at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.doInBackground(BitmapLoadingWorkerTask.java:87) 
                                                                at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.doInBackground(BitmapLoadingWorkerTask.java:26) 
                                                                at android.os.AsyncTask$2.call(AsyncTask.java:288) 
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                at java.lang.Thread.run(Thread.java:841) 
                                                             Caused by: libcore.io.ErrnoException: open failed: ENOENT (No such file or directory)
                                                                at libcore.io.Posix.open(Native Method)
                                                                at libcore.io.BlockGuardOs.open(BlockGuardOs.java:110)
                                                                at libcore.io.IoBridge.open(IoBridge.java:393)
                                                                at java.io.FileInputStream.<init>(FileInputStream.java:78) 
                                                                at java.io.FileInputStream.<init>(FileInputStream.java:105) 
                                                                at android.content.ContentResolver.openInputStream(ContentResolver.java:627) 
                                                                at com.theartofdev.edmodo.cropper.BitmapUtils.decodeImageForOption(BitmapUtils.java:268) 
                                                                at com.theartofdev.edmodo.cropper.BitmapUtils.decodeSampledBitmap(BitmapUtils.java:117) 
                                                                at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.doInBackground(BitmapLoadingWorkerTask.java:87) 
                                                                at com.theartofdev.edmodo.cropper.BitmapLoadingWorkerTask.doInBackground(BitmapLoadingWorkerTask.java:26) 
                                                                at android.os.AsyncTask$2.call(AsyncTask.java:288) 
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                at java.lang.Thread.run(Thread.java:841)

**Comment by ArthurHub** [comment]
File not found, it is possible that the camera app failed to save the captured image
Try changing the path

**Comment by lingboo** [comment]
Thank you, but i don't see any wrong in my Uri or file path. I go into my file manager in my device and see the file display, and in android studio still error.

**Comment by ArthurHub** [comment]
ok... but is changing the path works?
The library doesn't do anything special, it just opens the stream to the file so I'm not sure how I can help

**Comment by lingboo** [comment]
Ok, thanks for fast reply. :+1:

**Comment by mm-farag** [comment]
I have the same issue as well ! working on build tools 26.0.2, support version 26.1.0.
