### ISSUE TITLE
Null pointer exception on getting parcelable from Bundle

### ISSUE THREAD

**Issue by kkogut95** [ArthurHub/Android-Image-Cropper#753]
### Device
 Defy Mini - Android 5.0.2
### Steps to reproduce
Issue from Creashnalytics, steps unknown
### Logs
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
       at com.theartofdev.edmodo.cropper.CropImageActivity.onCreate(CropImageActivity.java:63)
       at android.app.Activity.performCreate(Activity.java:5937)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by SahilGargCrownStack** [comment]
i am facing same issue, please reply

**Comment by fAntel** [comment]
This is duplicate of #551 and #616 . There is already [PR](https://github.com/ArthurHub/Android-Image-Cropper/pull/645) since Jan 23, 2019

**Comment by Canato** [comment]
Hey!

I start a new project to handover this library
https://github.com/CanHub/Android-Image-Cropper

The ideia is that we keep improving because this project don’t have updates since `2018` 
Hope I can count with your help.

Open to contribute, next pieces of work will be Android 11 permissions, refactor into Kotlin and ActivityContract
