### ISSUE TITLE
Getting InflateException when opening the cropper with theme with ActionBar

### ISSUE THREAD

**Issue by Coletz** [ArthurHub/Android-Image-Cropper#78]
If I use a theme without action bar, the activity starts with no problem. If I use a theme with action bar, I get an inflate exception (problem with Toolbar). Here the full stacktrace

`FATAL EXCEPTION: main
                                                                   Process: com.company.app, PID: 2863
                                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{com.company.app/com.theartofdev.edmodo.cropper.CropImageActivity}: android.view.InflateException: Binary XML file line #36: Error inflating class android.support.v7.widget.Toolbar
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java)
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java)
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java)
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java)
                                                                       at android.os.Handler.dispatchMessage(Handler.java)
                                                                       at android.os.Looper.loop(Looper.java)
                                                                       at android.app.ActivityThread.main(ActivityThread.java)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
                                                                    Caused by: android.view.InflateException: Binary XML file line #36: Error inflating class android.support.v7.widget.Toolbar
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java)
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java)
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java)
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java)
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:394)
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277)
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
                                                                       at com.theartofdev.edmodo.cropper.CropImageActivity.onCreate(CropImageActivity.java:49)
                                                                       at android.app.Activity.performCreate(Activity.java)
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java)
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java) 
                                                                       at android.os.Looper.loop(Looper.java) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                       at java.lang.reflect.Constructor.newInstance(Native Method)
                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java) 
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java) 
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java) 
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:394) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277) 
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                       at com.theartofdev.edmodo.cropper.CropImageActivity.onCreate(CropImageActivity.java:49) 
                                                                       at android.app.Activity.performCreate(Activity.java) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java) 
                                                                       at android.os.Looper.loop(Looper.java) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) 
                                                                    Caused by: java.lang.NoClassDefFoundError: android.support.graphics.drawable.VectorDrawableCompat
                                                                       at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:891)
                                                                       at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:356)
                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
                                                                       at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:192)
                                                                       at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
                                                                       at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
                                                                       at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
                                                                       at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                                       at android.view.LayoutInflater.createView(LayoutInflater.java) 
                                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java) 
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java) 
                                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java) 
                                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:394) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312) 
                                                                       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:277) 
                                                                       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
                                                                       at com.theartofdev.edmodo.cropper.CropImageActivity.onCreate(CropImageActivity.java:49) 
                                                                       at android.app.Activity.performCreate(Activity.java) 
                                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java) 
                                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java) 
                                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java) 
                                                                       at android.app.ActivityThread.access$800(ActivityThread.java) 
                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java) 
                                                                       at android.os.Handler.dispatchMessage(Handler.java) 
                                                                       at android.os.Looper.loop(Looper.java) 
                                                                       at android.app.ActivityThread.main(ActivityThread.java) 
                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java) 
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java) `

**Comment by Coletz** [comment]
not related to this project, sorry about that
