### ISSUE TITLE
RuntimeException: CropImageActivity.java line 63

### ISSUE THREAD

**Issue by walkmn** [ArthurHub/Android-Image-Cropper#780]
Hi developers. I'm using your library, thanks for that. But recently I got a crash from firebase crashlitics, here is details:

Device Model: **Nexus 6**
Operating System Version: **7.1.1**
```
Non-fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.my.package/com.theartofdev.edmodo.cropper.CropImageActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)

```

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
       at com.theartofdev.edmodo.cropper.CropImageActivity.onCreate(CropImageActivity.java:63)
       at android.app.Activity.performCreate(Activity.java:6679)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
       at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
```

I cann't reproduce this on my device, but I think you can add safety code for this case.

**Comment by vineed** [comment]
Got same error on Android 8 device

**Comment by mirono** [comment]
Got same error from Nexus5X OS 8.1.0

**Comment by zackd** [comment]
same issue. Nexus 4, Android 6.0.1

**Comment by fAntel** [comment]
This is duplicate of #551 and #616 . There is already [PR](https://github.com/ArthurHub/Android-Image-Cropper/pull/645) since Jan 23, 2019

**Comment by Canato** [comment]
Hey!

I start a new project to handover this library
https://github.com/CanHub/Android-Image-Cropper

The ideia is that we keep improving because this project don’t have updates since `2018` 
Hope I can count with your help.

Open to contribute, next pieces of work will be Android 11 permissions, refactor into Kotlin and ActivityContract
