### ISSUE TITLE
Issue reported by Crashlytics at CropImageActivity.java:63

### ISSUE THREAD

**Issue by ali-nahid** [ArthurHub/Android-Image-Cropper#802]
Brand: LGE
Model: Nexus 4
Orientation: Portrait
RAM free: 1.03 GB
Disk free: 268.67 MB
Operating System: Android
Version: 6.0.1
Orientation: Portrait
Rooted: No

Stack Trace
--
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.seveni.beingnurse.nurses/com.theartofdev.edmodo.cropper.CropImageActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Parcelable android.os.Bundle.getParcelable(java.lang.String)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2419)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2479)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1347)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Canato** [comment]
Hey!

I start a new project to handover this library
https://github.com/CanHub/Android-Image-Cropper

The ideia is that we keep improving because this project don’t have updates since `2018` 
Hope I can count with your help.

Open to contribute, next pieces of work will be Android 11 permissions, refactor into Kotlin and ActivityContract
