### ISSUE TITLE
NullPointerException in hasPermissionInManifest()

### ISSUE THREAD

**Issue by trramsiq** [ArthurHub/Android-Image-Cropper#94]
## Just experienced this crash on a SM-G925F running 6.0.1

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.Context.getPackageName()' on a null object reference
       at com.theartofdev.edmodo.cropper.CropImage.hasPermissionInManifest(CropImage.java:263)
       at com.theartofdev.edmodo.cropper.CropImage.isExplicitCameraPermissionRequired(CropImage.java:250)
       at com.mypackage.ProfilePictureFragment$3.onClick(ProfilePictureFragment.java:197)
       at com.android.internal.app.AlertController$AlertParams$3.onItemClick(AlertController.java:1227)
       at android.widget.AdapterView.performItemClick(AdapterView.java:345)
       at android.widget.AbsListView.performItemClick(AbsListView.java:1547)
       at android.widget.AbsListView$PerformClick.run(AbsListView.java:3821)
       at android.widget.AbsListView$3.run(AbsListView.java:5841)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:158)
       at android.app.ActivityThread.main(ActivityThread.java:7224)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
```

`197. requestPermissions(new String[]{Manifest.permission.CAMERA}, CropImage.CAMERA_CAPTURE_PERMISSIONS_REQUEST_CODE);`

**Comment by trramsiq** [comment]
The complete code is:
```
196. if (CropImage.isExplicitCameraPermissionRequired(getActivity())) {
197. requestPermissions(new String[]{Manifest.permission.CAMERA}, CropImage.CAMERA_CAPTURE_PERMISSIONS_REQUEST_CODE);
198. }
```

So getActivity() is passing a null pointer to 'isExplicitCameraPermissionRequired'?
