### ISSUE TITLE
Crash on ViewDragHelper.java ArrayIndexOutOfBoundsException index 1, size 1

### ISSUE THREAD

**Issue by nguyenvp08** [ArthurHub/Android-Image-Cropper#95]
I have tried to use the library, but the Fabric crashlytics logged this bug occurred many times. In my app, i use DrawerLayout for left side menu, can you help to take a look into this bug.

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=1; index=1
       at android.support.v4.widget.ViewDragHelper.saveLastMotion(ViewDragHelper.java:849)
       at android.support.v4.widget.ViewDragHelper.shouldInterceptTouchEvent(ViewDragHelper.java:1057)
       at android.support.v4.widget.DrawerLayout.onInterceptTouchEvent(DrawerLayout.java:1434)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1908)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2037)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2343)

**Comment by ArthurHub** [comment]
It doesn't seems to be related to the cropper library, why do you think otherwise?

**Comment by nguyenvp08** [comment]
Hi thanks for your reply,
I just used your library recently and, this issue occurred right after I tried to integrate your cropper ImageView, and then I searched for the crash on Stackoverflow, there are some other Zoom Image library got this issue, so I think that somehow your library could cause this.
I just use the CropImageView and set the image bitmap, It's happened almost on Samsung devices

**Comment by ArthurHub** [comment]
The sample app in the library also uses `DrawerLayout`, see if it works for you.
I still don't think it is related to the library but if you create a minimum viable project that reproduces this issue I will take a look.

**Comment by aarnold** [comment]
Also seeing this problem as soon as I integrate the project

**Comment by ArthurHub** [comment]
can you post sample code?

**Comment by aarnold** [comment]
looks like an id clash with "drawer_layout", just changing mine fixed it

**Comment by ArthurHub** [comment]
but the library doesn't use this id...
also the sample app uses it and there is no collision...

@nguyenvp08 can you check if it fixes your issue too.

**Comment by nguyenvp08** [comment]
hi @ArthurHub : now I am trying to change the drawer layout id, I also used this id for my app, after testing, I will inform you, thank you and @aarnold so much.

**Comment by ArthurHub** [comment]
did it work?

**Comment by nguyenvp08** [comment]
Hi, I just uploaded the APK 2 days ago, up to now this bug not happened again, I hope the solution works, I will close the issue, thank you all very much!
